import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
    {
      type:'category',
      label:'チュートリアル',
      items:[{type:'autogenerated',dirName:'tutorial-basics'}],
      collapsed: false
    },
    {
      type:'category',
      label:'翻訳データ共有',
      items:[{type:'autogenerated',dirName:'share-data'}],
      collapsed: false
    },
    {
      type:'category',
      label:'スクリプト連携',
      items:[{type:'autogenerated',dirName:'scripting'}],
      collapsed: false
    },
    {
      type:'category',
      label:'API',
      items:[{type:'autogenerated',dirName:'api'}]
    },
  ],
};

export default sidebars;
